# Generated by Django 3.1.4 on 2020-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_series', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=50)),
                ('movie_link', models.CharField(max_length=300)),
                ('number_of_episodes', models.IntegerField()),
            ],
        ),
    ]
