# Generated by Django 2.2.1 on 2021-01-04 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Image_Link', models.ImageField(upload_to='media/images')),
                ('Product_Price', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Orders', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('Order_Status', models.CharField(choices=[('new', 'NEW'), ('paid', 'PAID')], default='new', max_length=20)),
                ('Mode_of_Payment', models.CharField(choices=[('cash', 'CASH'), ('paytm', 'PAYTM'), ('card', 'CARD')], default='cash', max_length=30)),
                ('Products', models.ManyToManyField(to='productsapp.ProductsData')),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Items_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.OrdersData')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.ProductsData')),
            ],
        ),
    ]
