# Generated by Django 2.2.1 on 2021-01-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20210107_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdata',
            name='Image_Link',
            field=models.ImageField(upload_to='./frontend/public/images'),
        ),
    ]
