# Generated by Django 2.2.1 on 2021-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_auto_20210107_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdata',
            name='Image_Link',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
